#!/bin/sh

set -e

if [ "$1" = "upgrade" ] ; then
    rm -f /usr/bin/linoleum
    rm -f /usr/share/linoleum/lib/ivy.jar
    rm -f /usr/share/linoleum/lib/commons-codec.jar
    rm -f /usr/share/linoleum/lib/jsch.jar
    rm -f /usr/share/linoleum/lib/javax.mail.jar
fi

exit 0
