#!/bin/sh

set -e

if [ "$1" = "upgrade" ] ; then
    rm /usr/bin/linoleum
    rm /usr/share/linoleum/lib/ivy.jar
    rm /usr/share/linoleum/lib/commons-codec.jar
    rm /usr/share/linoleum/lib/jsch.jar
fi

exit 0
