package linoleum.application;

import java.io.File;
import java.net.URI;
import java.nio.file.Paths;
import java.util.HashMap;
import java.util.Map;
import java.util.ServiceLoader;
import javax.swing.DefaultListModel;
import javax.swing.JInternalFrame;

public class ApplicationManager extends javax.swing.JInternalFrame {
	public static final ApplicationManager instance = new ApplicationManager();
	private final Map<String, Application> map = new HashMap<String, Application>();
	private final DefaultListModel model = new DefaultListModel();
	private static final String text[] = {"txt", "log", "properties", "js", "scala", "java"};
	private static final String image[] = {"gif", "jpg", "png"};

	private static boolean hasExt(final File file, final String ext[]) {
		for (final String s : ext) {
			if (file.getName().endsWith("." + s)) {
				return true;
			}
		}
		return false;
	}

	private ApplicationManager() {
		initComponents();
		refresh();
	}

	public void open(final URI uri) {
		final File file = Paths.get(uri).toFile();
		if (hasExt(file, text)) {
			open("Notepad", file);
		} else if (hasExt(file, image)) {
			open("ImageViewer", file);
		} else if (file.isDirectory()) {
			open("FileManager", file);
		}
	}

	private void open(final String name, final File file) {
		final Application app = map.get(name);
		if (app != null) open(app, file == null?null:file.toURI());
	}

	private void open(final Application app, final URI uri) {
		JInternalFrame frame = app.open(uri);
		getDesktopPane().add(frame);
		frame.setVisible(true);
	}

	private void open(final int index) {
		open((String)model.getElementAt(index), null);
	}

	public final void refresh() {
		ServiceLoader<Application> loader = ServiceLoader.load(Application.class);
		map.clear();
		model.clear();
		for (final Application app: loader) {
			map.put(app.getName(), app);
			model.addElement(app.getName());
		}
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jScrollPane1 = new javax.swing.JScrollPane();
                jList1 = new javax.swing.JList();

                setClosable(true);
                setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
                setIconifiable(true);
                setMaximizable(true);
                setResizable(true);
                setTitle("Applications");

                jList1.setModel(model);
                jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
                jList1.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                jList1MouseClicked(evt);
                        }
                });
                jScrollPane1.setViewportView(jList1);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
		if (evt.getClickCount() == 2) {
			open(jList1.locationToIndex(evt.getPoint()));
		}
        }//GEN-LAST:event_jList1MouseClicked


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JList jList1;
        private javax.swing.JScrollPane jScrollPane1;
        // End of variables declaration//GEN-END:variables
}
